name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.4.1
  firebase_auth: 4.2.1
  lottie: 2.1.0
  introduction_screen: 3.1.1
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.5.1
  google_sign_in: 5.4.2
  get_storage: 2.0.3
  cloud_firestore: 4.3.0
  intl: 0.18.0
  image_picker: 0.8.6
  firebase_storage: 11.0.10
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

