// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBODvaP0_oWcw0DJas5DKgej_0WXTXqxI4',
    appId: '1:349889688653:android:cddee247480b30a70b5804',
    messagingSenderId: '349889688653',
    projectId: 'presence-app-c2764',
    databaseURL: 'https://presence-app-c2764-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'presence-app-c2764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxSEVRk67lCImD9cGNl6yzIdF0UUZWjXA',
    appId: '1:349889688653:ios:5137849764c837a70b5804',
    messagingSenderId: '349889688653',
    projectId: 'presence-app-c2764',
    databaseURL: 'https://presence-app-c2764-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'presence-app-c2764.appspot.com',
    iosClientId: '349889688653-1k1udg0580vhfps5h4d4qv91b887jqqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceApp',
  );
}
